### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by etherbiswas** [cafetestrest/nixos#1]
Did you manage to get https://github.com/Aylur/dotfiles fully working on nix?

**Comment by etherbiswas** [comment]
If so, do all the ags widgets work on the nix install?

**Comment by cafetestrest** [comment]
Hi @etherrorcode404 ,
Well yeah, removed some stuff here and there that I didn't like or these that are not needed for my case.
Mostly brightnessctl and asusctl references.

As for the nix part, I'm using NixOS with flakes, so just added new input for ags worked for me.
Here is the flake.nix file with ags reference: https://github.com/cafetestrest/nixos/blob/main/flake.nix

**Comment by cafetestrest** [comment]
Also, make sure you remove brightness.js from modules folder along with all other references to the brightness in the dotfiles in case you did not install brightnessctl like me.

You can always start by copying 2 files from within example folder and keep adding new functionalities from there.
