### ISSUE TITLE
Notification Center only shows the last message

### ISSUE THREAD

**Issue by acdcbyl** [cafetestrest/nixos#2]
There is only the last message inside the popwindow of the notification, and I checked the logs and found
 ```
(GJS:5817): Gjs-CRITICAL **: 10:30:55.056: Object .Revealer (0x628d1de4e350), has been already disposed of - impossible to access it. This is probably due to destroying the object in C code using methods like This may be due to the destruction of the object in C code using methods such as destroy(), dispose() or remove() vfuncs.
== Stack trace for context 0x628d1ce45a40 ==
#0 7ffc16bd4f80 b file:///run/user/1000/ags.js:749 (2689c44a4920 @ 29)
#1 7ffc16bd5040 b file:////run/user/1000/ags.js:498 (2689c44a36a0 @ 290)
#2 7ffc16bd5710 b file:////run/user/1000/ags.js:350 (2689c44a2ce0 @ 16)
#3 7ffc16bd5c80 b file:////run/user/1000/ags.js:51 (2689c44a0150 @ 21)
#4 7ffc16bd5d30 b file:////run/user/1000/ags.js:218 (2689c44a22e0 @ 21)
#5 7ffc16bd6a60 b file:////run/user/1000/ags.js:160 (2689c44a0c40 @ 63)
#6 628d1cf39850 i file:////run/user/1000/ags.js:5069 (2689c44b3380 @ 137)
#7 628d1cf397b8 i file:////run/user/1000/ags.js:5093 (2689c44b35b0 @ 104)
#8 628d1cf39700 i file:////run/user/1000/ags.js:5075 (2689c44b3420 @ 77)
#9 628d1cf39638 i resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263 (2689c44c68d0 @ 139)
```
I'd like to know if anyone else is having this problem.

**Comment by cafetestrest** [comment]
I'm not sure 100% what you are referring to?

I'm removing all previous notifications on first start of ags on the line here: https://github.com/cafetestrest/nixos/blob/23f63fe4e7473a7886d7d977f95920da3310d87b/config/ags/widget/Notifications/index.tsx#L59

And on the topbar revealer there will be only last notification visible.

I'm able to see all Notifications in their own popup, mainly I test them like so:
```
notify-send "summary" "body"
```

![image](https://github.com/user-attachments/assets/7f02accd-8a73-4a95-83ab-76d4c1c5389f)

Also these are my own dotfiles not a real public project, I'm not planning it to be.

**Comment by acdcbyl** [comment]
> I'm not sure 100% what you are referring to?
> 
> I'm removing all previous notifications on first start of ags on the line here: https://github.com/cafetestrest/nixos/blob/23f63fe4e7473a7886d7d977f95920da3310d87b/config/ags/widget/Notifications/index.tsx#L59
> 
> And on the topbar revealer there will be only last notification visible.
> 
> I'm able to see all Notifications in their own popup, mainly I test them like so:
> ```
> notify-send "summary" "body"
> ```
> 
> ![image](https://github.com/user-attachments/assets/7f02accd-8a73-4a95-83ab-76d4c1c5389f)
> 
> Also these are my own dotfiles not a real public project, I'm not planning it to be.

Thank you very much, analyzing by your screenshots is what's wrong with me here...I think I'll try to fix it by myself.
